name: Jekyll Algolia

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Updates Algolia indicies
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && bundle install && ALGOLIA_API_KEY=${{ secrets.ALGOLIA_ADMIN_API_KEY }} bundle exec jekyll algolia"
